### ISSUE TITLE
Get the payee details to the backend

### ISSUE THREAD

**Issue by Prade7** [Subhamsaurav/razorpay-flask-integration#1]
Your code helps me a lot but the payee details such as payee name and payee email should be sent to backend for adding it in the db

**Comment by nonesubham** [comment]
sure i will update it very soon. 😊

**Comment by nonesubham** [comment]
> Your code helps me a lot but the payee details such as payee name and payee email should be sent to backend for adding it in the db



> Your code helps me a lot but the payee details such as payee name and payee email should be sent to backend for adding it in the db

sure i will update it very soon. 😊
